# azure-pipelines.yml
trigger: none

parameters:
  - name: "ENVIRONMENT"
    displayName: "Environment"
    type: string
    values:
      - "dev"
      - "uat"
    default: "uat"
  - name: "TEST_TYPE"
    displayName: "Test type"
    type: string
    values:
      - "load"
      - "smoke"
      - "soak"
      - "spike"
      - "stress"
      - "constant"
    default: "constant"
  - name: "SCRIPT"
    displayName: "Script name"
    type: string
    values:
      - nodoInviaRPT_workflow
variables:
  ${{ if eq(parameters['ENVIRONMENT'], 'dev') }}:
    poolImage: 'pagopa-dev-loadtest-linux'
    NODO_PA_SUBSCRIPTION_KEY: $(DEV_NODO_PA_SUBSCRIPTION_KEY)
    STATION_PWD: $(DEV_STATION_PASSWORD)
    CHANNEL_PWD: $(DEV_CHANNEL_PASSWORD)
  ${{ if eq(parameters['ENVIRONMENT'], 'uat') }}:
    poolImage: 'pagopa-uat-loadtest-linux'
    NODO_PA_SUBSCRIPTION_KEY: $(UAT_NODO_PA_SUBSCRIPTION_KEY)
    STATION_PWD: $(UAT_STATION_PASSWORD)
    CHANNEL_PWD: $(UAT_CHANNEL_PASSWORD)


pool:
  name: $(poolImage)

steps:
  - script: |
      cd ./performance-test/src
      docker pull grafana/k6
    displayName: Pull k6 image

  - script: |
      cd ./performance-test
      sh ./run_performance_test.sh ${{ parameters.ENVIRONMENT }} ${{ parameters.TEST_TYPE }} ${{ parameters.SCRIPT }} wispsoapconvk6 $(NODO_PA_SUBSCRIPTION_KEY) $(STATION_PWD) $(CHANNEL_PWD)
    displayName: Run k6 ${{ parameters.SCRIPT }} on ${{ parameters.ENVIRONMENT }}
