microservice-chart:
  namespace: "nodo"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-wisp-converter
    tag: "0.1.22-12-PAGOPA-2125"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 180
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 180
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weudev.nodo.internal.dev.platform.pagopa.it"
    path: /pagopa-wisp-converter(/|$)(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "256Mi"
      cpu: "0.15"
    limits:
      memory: "768Mi"
      cpu: "0.25"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    WEBSITE_SITE_NAME: 'pagopawispconverter' # required to show cloud role name in application insights
    ENV: 'aks-dev'
    APP_LOGGING_LEVEL: 'DEBUG'
    APP_LOGGING_TRACING_LEVEL: 'ERROR'
    DEFAULT_LOGGING_LEVEL: 'INFO'
    CORS_CONFIGURATION: '{"origins": ["*"], "methods": ["*"]}'
    OTEL_SERVICE_NAME: "pagopa-wisp-converter"
    OTEL_RESOURCE_ATTRIBUTES: "service.environment=dev"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    REDIS_PORT: "6380"
    COSMOS_URI: "https://pagopa-d-weu-nodo-wispconv-cosmos-account.documents.azure.com:443/"
    PAAINVIART_SERVICE_BUS_NAME: "nodo_wisp_paainviart_queue"
    RECEIPT_TIMER_QUEUE_NAME: "nodo_wisp_payment_timeout_queue"
    ECOMMERCE_HANG_TIMER_QUEUE_NAME: "nodo_wisp_ecommerce_hang_timeout_queue"
    ECOMMERCE_HANG_TIMEOUT: '1800'
    CACHED_REQUESTID_MAPPING_TTL_MINUTES: "1440"
    CACHE_REFRESH_CRON: "0 */60 * * * *"
    CLIENT_GPD_READ_TIMEOUT: '5000'
    CLIENT_IUVGENERATOR_READ_TIMEOUT: '5000'
    CLIENT_CHECKOUT_READ_TIMEOUT: '5000'
    CLIENT_DECOUPLERCACHING_READ_TIMEOUT: '5000'
    CLIENT_CACHE_READ_TIMEOUT: '5000'
    CLIENT_GPD_HOST: 'https://api.dev.platform.pagopa.it/gpd/api/v2'
    CLIENT_IUVGENERATOR_HOST: 'https://api.dev.platform.pagopa.it/shared/pagopa-iuvgenerator/v1'
    CLIENT_CHECKOUT_HOST: 'https://api.dev.platform.pagopa.it/checkout/carts-auth/v1'
    CLIENT_DECOUPLERCACHING_HOST: 'https://api.dev.platform.pagopa.it/wisp-converter/caching/api/v1'
    CLIENT_CACHE_HOST: 'https://api.dev.platform.pagopa.it/api-config-cache/p/v1'
    STATION_IN_GPD_PARTIAL_PATH: 'gpd-payments/api/v1'
    RT_SEND_MAX_RETRIES: '48'
    RT_SEND_SCHEDULING_TIME_IN_MINUTES: '1'
    RT_SEND_AVOID_SCHEDULING_ON_STATES: 'PAA_RT_DUPLICATA'
    RPT_TIMER_QUEUE_NAME: "nodo_wisp_rpt_timeout_queue"
    RPT_TIMEOUT: '1800'
    RE_TRACING_INTERFACE_IUVGENERATOR_ENABLED: 'true'
    RE_TRACING_INTERFACE_PAYMENTPOSITIONANALYSIS_ENABLED: 'true'
    RE_TRACING_INTERFACE_DECOUPLERCACHING_ENABLED: 'true'
    RE_TRACING_INTERFACE_CHECKOUTINTERACTION_ENABLED: 'true'
    RE_TRACING_INTERNAL_RPTRETRIEVING_ENABLED: 'true'
    RE_TRACING_INTERNAL_RTRETRIEVING_ENABLED: 'true'
    RE_TRACING_INTERNAL_RPTEXTRACTION_ENABLED: 'true'
    RE_TRACING_INTERNAL_PAYMENTPOSITIONANALYSIS_ENABLED: 'true'
    RE_TRACING_INTERNAL_DECOUPLERCACHING_ENABLED: 'true'
    RE_TRACING_INTERNAL_CHECKOUTINTERACTION_ENABLED: 'true'
    SPRING_PROFILES_ACTIVE: "default,jsonLog"
  secretProvider:
    create: true
    envSecrets:
      # required
      APPLICATIONINSIGHTS_CONNECTION_STRING: 'azure-insight-connection-string'
      SERVICE_BUS_PAYMENT_TIMEOUT_QUEUE_CONNECTION_STRING: 'wisp-payment-timeout-queue-connection-string'
      SERVICE_BUS_PAAINVIART_QUEUE_CONNECTION_STRING: 'wisp-paainviart-queue-connection-string'
      ECOMMERCE_HANG_TIMER_QUEUE_CONNECTION_STRING: 'ecommerce-hang-timer-queue-connection-string'
      RPT_TIMER_QUEUE_CONNECTION_STRING: 'wisp-rpt-timeout-queue-connection-string'
      OTEL_EXPORTER_OTLP_HEADERS: elastic-apm-secret-token
      REDIS_PASSWORD: 'redis-primary-key'
      REDIS_HOST: 'redis-hostname'
      COSMOS_KEY: 'cosmosdb-wisp-converter-account-key'
      CLIENT_GPD_SUBKEY: 'gpd-pagopa-v1-subscription-key'
      CLIENT_IUVGENERATOR_SUBKEY: 'iuv-generator-subscription-key'
      CLIENT_DECOUPLERCACHING_SUBKEY: 'wisp-converter-caching-subscription-key'
      CLIENT_CACHE_SUBKEY: 'api-config-cache-subscription-key-string'
      CLIENT_CHECKOUT_SUBKEY: 'checkout-subscription-key-string'
      FORWARDER_SUBKEY: 'node-forwarder-subscription-key-string'
    keyvault:
      name: "pagopa-d-nodo-kv"
      tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  tmpVolumeMount:
    create: true
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/pagopa-wisp-converter
        tag: "0.0.0"
        pullPolicy: Always
      envConfig: {}
      envSecret: {}
