microservice-chart:
  namespace: "nodo"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-wisp-converter
    tag: "0.0.14-1-fixes"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuuat.nodo.internal.uat.platform.pagopa.it"
    path: /pagopa-wisp-converter(/|$)(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "768Mi"
      cpu: "0.50"
    limits:
      memory: "768Mi"
      cpu: "0.50"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    WEBSITE_SITE_NAME: 'pagopawispconverter' # required to show cloud role name in application insights
    ENV: 'aks-uat'
    APP_LOGGING_LEVEL: 'INFO'
    DEFAULT_LOGGING_LEVEL: 'INFO'
    CORS_CONFIGURATION: '{"origins": ["*"], "methods": ["*"]}'
    OTEL_SERVICE_NAME: "pagopa-wisp-converter"
    OTEL_RESOURCE_ATTRIBUTES: "service.environment=uat"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    REDIS_HOST: "pagopa-u-redis.redis.cache.windows.net"
    REDIS_PORT: "6380"
    COSMOS_URI: "https://pagopa-u-weu-nodo-wispconv-cosmos-account.documents.azure.com:443/"
    CACHED_REQUESTID_MAPPING_TTL_MINUTES: "1440"
    CACHE_REFRESH_CRON: "0 */60 * * * *"
    CLIENT_GPD_READ_TIMEOUT: '5000'
    CLIENT_IUVGENERATOR_READ_TIMEOUT: '5000'
    CLIENT_CHECKOUT_READ_TIMEOUT: '5000'
    CLIENT_DECOUPLERCACHING_READ_TIMEOUT: '5000'
    CLIENT_CACHE_READ_TIMEOUT: '5000'
    CLIENT_GPD_HOST: 'https://api.uat.platform.pagopa.it/gpd/api/v1'
    CLIENT_IUVGENERATOR_HOST: 'https://api.uat.platform.pagopa.it/shared/pagopa-iuvgenerator/v1'
    CLIENT_CHECKOUT_HOST: 'https://api.uat.platform.pagopa.it/checkout/ec/v1/'
    CLIENT_DECOUPLERCACHING_HOST: 'https://api.uat.platform.pagopa.it/wisp-converter/caching/api/v1'
    CLIENT_CACHE_HOST: 'https://api.uat.platform.pagopa.it/api-config-cache/o/v1'
  secretProvider:
    create: true
    envSecrets:
      # required
      APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-u-connection-string'
      OTEL_EXPORTER_OTLP_HEADERS: elastic-apm-secret-token
      REDIS_PASSWORD: 'redis-primary-key'
      COSMOS_KEY: 'cosmosdb-wisp-converter-account-key'
      CLIENT_GPD_SUBKEY: 'gpd-pagopa-v1-subscription-key'
      CLIENT_IUVGENERATOR_SUBKEY: 'iuv-generator-subscription-key'
      CLIENT_DECOUPLERCACHING_SUBKEY: 'wisp-converter-caching-subscription-key'
      CLIENT_CACHE_SUBKEY: 'api-config-cache-subscription-key-string'
    keyvault:
      name: "pagopa-u-nodo-kv"
      tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  tmpVolumeMount:
    create: true
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/pagopa-wisp-converter
        tag: "0.0.0"
        pullPolicy: Always
      envConfig: {}
      envSecret: {}
